### ISSUE TITLE
C++ tokeniser is/has been broken

### ISSUE THREAD

**Issue by dah33** [vonox7/golfcoder#17]
The following is 16 tokens, of which most are the header for `iostream`:

https://golfcoder.org/2023/day/1?solution=e662d399dfd61f751247ea083f0cc2d3#solution

```
#include<iostream>
#defineXusing namespace std; int main() {string line;uint32_t sum{};while (getline(cin, line)) {uint32_t d = 0;for (auto c : line)if (c < 60) {auto x = c - 48;if (!d) sum += 10 * x;d = x;}sum += d;}cout << sum << endl;}
X
```

**Comment by vonox7** [comment]
Hi dah33, thank you for the report!
You are right, there are 2 problems, I'll take a look into that!

**Comment by vonox7** [comment]
@dah33 https://golfcoder.org/2023/day/1?solution=e662d399dfd61f751247ea083f0cc2d3#solution now correctly reports 87 tokens
