### ISSUE TITLE
Internal server error for GH auth

### ISSUE THREAD

**Issue by tbeu** [vonox7/golfcoder#19]
Linking a GitHub account reseults in 500:
```
500: io.ktor.serialization.JsonConvertException: Illegal input: Unexpected JSON token at offset 868: Unexpected 'null' value instead of string literal at path: $.name
JSON input: ....."site_admin":false,"name":null,"company":null,"blog":"","loc.....
```

**Comment by vonox7** [comment]
Hi @tbeu, thank you for the report. I didn't know that GitHub profiles without a name exist. The issue should now be fixed, can you please try it again? Thank you!

**Comment by tbeu** [comment]
Confirmed. Thanks. I have more one one GH account and need to select which one to use.
