### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by dah33** [vonox7/golfcoder#20]
More of a suggestion than an issue. 

OneCompiler reports Python `sys.version` as:

```
3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
```
This is quite old, and doesn't include `match` which is commonly used in recent code golfing.

**Comment by vonox7** [comment]
Yes, you are right. It seems like [OneCompiler](https://onecompiler.com/) supports only Python 3.8.10. I'll have a look to other online compilers that have an API which support newer Python versions. @dah33  do you have any recommendation which one to use? I found now mycompiler.io, which seems to use at least Python 3.11.4.

**Comment by dah33** [comment]
I don't know online interpreters that well. I would wait until you've got more users and see what other feedback is like. I would think Python would be quite popular, but actually a lot of the early submissions are Kotlin.

**Comment by LiquidFun** [comment]
I would appreciate 3.9+ as well! `math.lcm` is relatively [new](https://docs.python.org/3/library/math.html#math.lcm) in Python and quite useful for golfing. Thank you!

I looked at a couple others, like ideone.com which was a bit older as well (3.9) or repl.it which seems overkill. So, mycompiler.io seems promising.

**Comment by vonox7** [comment]
Good news! OneCompiler has updated the python version. Now Golfcoder supports Python **3.12.3** (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
