### ISSUE TITLE
Language support: Bash

### ISSUE THREAD

**Issue by Mechazawa** [vonox7/golfcoder#22]
I have some pretty short solutions using bash that I'd love to submit

**Comment by vonox7** [comment]
Hey @Mechazawa, I added bash. Feel free to try it! :)

**Comment by Mechazawa** [comment]
Thanks! I found some slight issues with it. For some reason it's not accepting this solution for day3 part 1

```bash
echo $(($(cat | grep -oE mul\\\(\\d+,\\d+\)|tr -s ,mul \*+)))
```

also the way it's counting tokens doesn't seem very fair. Since It's counting strings as one token per character `"this is 18 token"` but if you type it using escapes it counts as a single token `this\ is\ a\ single\ token`. Which would allow for chenanigans such as `bash -c echo\ one\ very\ long\ token\;echo\ hello\ world`
