### ISSUE TITLE
Cheating is still possible

### ISSUE THREAD

**Issue by Sharparam** [vonox7/golfcoder#23]
See the 4 token "solutions" on day 1: https://golfcoder.org/2024/day/1?solution=629cf44b9d5361856ea115157efffd9e#solution

This needs to be fixed.

**Comment by vonox7** [comment]
The mentioned 4 token "solution" is banned.

**Comment by Sharparam** [comment]
@vonox7 Has the underlying issue been fixed? (That users can submit solutions that just output the example answer and that lets them pass.)

**Comment by vonox7** [comment]
Users could (and can always) create outputs that might be against the rules. However I have now a system in place where solutions can get banned. Thats a pragmatic desition and I decided that this is good enough for now.

**Comment by Sharparam** [comment]
I think it would be reasonable though that solutions would at least get checked against multiple inputs (example and one set of real inputs as a minimum). This would swiftly get rid of the simple cheats that just output a single answer.
